### ISSUE TITLE
Mini CW Key Automatic Morse (Paddle)

### ISSUE THREAD

**Issue by oxoocoffee** [jmharvey1/STM32_CWDecoder#2]
Hello,

This is a great project? I was wondering if there is a way to connect or make modification to add external Paddle for training purposes?

**Comment by jmharvey1** [comment]
Thanks for the question & apologize for not seeing it earlier.
There is a limited way to get what you're asking. But it requires you providing your own "side tone". If you look close at the wiring diagrams, you see that MPUs have two pins "jumpered" together. (on the BluePill its PA8 & PA9) That jumper is the dected tone out to decoder input. In this case PA8 is 'input' pin. You could open this link and connect a straight key or Bug directly to A8, and the decoder should operate (decode your key closures). For paddles you would need to provide extrenal logic to convert 'left' & 'right' contact closures into 'dit' & 'dah' strings
Again, thank you for your interest in the project
